### ISSUE TITLE
Deploy script should be able to support environment variables

### ISSUE THREAD

**Issue by Massfice** [Fairy-io/bun-vue-trpc-dev#8]
A lot of CI/CD providers adds environment variables to current running step.
E.g. Google Cloud Build has ability to access secrets as environment variables
```yaml
steps:
- name: python:slim
  entrypoint: python
  args: ['main.py']
  secretEnv: ['MYSECRET']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/mySecret/versions/latest
    env: 'MYSECRET'
```
([Use secrets from Secret Manager](https://cloud.google.com/build/docs/securing-builds/use-secrets))
However we have to still pass these variables as command parameters. We should be able to use environment variables. Command arguments should be optional, but take precedence over environment variables.
